version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123-
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-overlay

  app:
    image: my-golang-app
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: abc123-   # Thêm biến môi trường POSTGRES_PASSWORD để go có thể bắt được mật khẩu của postgres
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myapp.rule=Host(`myapp.com`)"
        - "traefik.http.services.myapp.loadbalancer.server.port=8088"
      replicas: 1      
    networks:
      - my-overlay

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - my-overlay

volumes:
  postgres_data:

networks:
  my-overlay:
    driver: overlay
