version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abc123-
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
