version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123-
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    networks:
      - my_network

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
